### PR TITLE
2fa

### PR DESCRIPTION
**Pull request by aLeuleu**
you can now enable 2fa for a player with /user/enable-2fa, this will give you a qr code that you can scan with an auth app.
You can then send a code and verify it to /user/verify-2fa.
you can disable 2fa for a player with /user/disable-2fa

Screenshot 2024-02-04 at 21 59 30
Screenshot 2024-02-04 at 21 59 42

### CODE REVIEW

**Comment by tdameros** [comment]
Don't you check whether the 2FA is activated at the time of signin?

**Comment by aLeuleu** [comment]
Yes I forgot to do that. Hopefully this won't take long

**Comment by tdameros** [comment]
Maybe rename the endpoints TOTP, because 2FA is a generic thing that can take any form.

**Comment by aLeuleu** [comment]
I disagree.
TOTP is one way to implement 2fa.
The goal of this endpoint isn't to provide a TOTP process, it is to provide a 2fa process.
API users shouldn't even have to worry about what TOTP or HOTP is.
API users should see a clear and simple endpoint to activate or deactivate the 2fa process.

**Review by EthanDelage — COMMENTED** [review]
In my opinion, to disable the 2fa, the user must send his 6-digit code.

**Review by EthanDelage — APPROVED** [review]

**Review by hferraud — APPROVED** [review]

**Pull request merged**
