### PR TITLE
Username endpoint

### PR DESCRIPTION
**Pull request by tdameros**
- Remove elo field
- Add the `/user/username/<str:username>/ `  endpoint to retrieve a user's public information using his username.

### CODE REVIEW

**Review by hferraud — APPROVED** [review]

**Comment by aLeuleu** [comment]
Provide description of what you did

**Review by aLeuleu — COMMENTED** [review]
The endpoint /user/<str:user_id:> was really meant to implement what you just did ! .. 

Screenshot 2024-02-05 at 11 24 11

In order to be more consistent, this is how the update should be :


Screenshot 2024-02-05 at 11 29 58

**Comment by aLeuleu** [comment]
the idea was to have only one endpoint

**Comment by aLeuleu** [comment]
image

**Comment by tdameros** [comment]
And if the user has only digit char in this username ?

**Comment by aLeuleu** [comment]
> And if the user has only digit char in this username ?

Not sure that something we really want.. Maybe we should prevent this.

If this is really an issue for you, you can merge this, I don't mind.

Otherwise, this is how we could have done it : 
https://github.com/tdameros/42-transcendence/pull/167

**Review by aLeuleu — APPROVED** [review]

**Pull request merged**
